version: '3'

services:
  postgres:
    image: postgres:13.1
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
  api:
    image: docker.dulik.net/aichan-backend:latest
    restart: always
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - ALLOW_CORS=true
    ports:
      - 9090:9090
    depends_on:
      - postgres
  frontend:
    image: docker.dulik.net/aichan-frontend:latest
    ports:
      - 8080:80
